name: geo-features
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - matplotlib
  - numpy
  - pytest
  - shapely
  - pip:
      - geoarrow-pyarrow
      - geoarrow-pandas
      - git+https://github.com/guidorice/mojo-pytest.git
