name: Run Tests

on: ["push"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          auto-activate-base: true

      - name: Install mojo
        run: |
          curl https://get.modular.com | MODULAR_AUTH=${{ secrets.MODULAR_AUTH }} sh -
          modular auth ${{ secrets.MODULAR_AUTH }}
          modular install mojo

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: geo-features
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false

      - name: Run mojo-pytest
        run: |
          export MODULAR_HOME="/home/runner/.modular"
          export PATH="/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH"
          export MOJO_PYTHON_LIBRARY="$(find $CONDA_PREFIX/lib -iname 'libpython*.[s,d]*' | sort -r | head -n 1)"
          $CONDA_PREFIX/bin/pytest -W error
